### ISSUE TITLE
warpgan8.mlmodel deserialize error

### ISSUE THREAD

**Issue by lihxCode** [william0wang/MagicCamera#1]
detail: validator error: unable to deserialize object
coremlc: error: Error reading protobuf spec. validator error: unable to deserialize object

**Comment by william0wang** [comment]
The mlmodel files use Git-lfs push to github. 
 You can download any missing Git LFS content with `git  lfs pull`

**Comment by william0wang** [comment]
> detail: validator error: unable to deserialize object coremlc: error: Error reading protobuf spec. validator error: unable to deserialize object

You can download models file from baidu pan or google drive now

**Comment by fengwang** [comment]
@william0wang I think you can upload those models to the release of this repo.

**Comment by william0wang** [comment]
> @william0wang I think you can upload those models to the release of this repo.

Thanks for your advice, I created a release with pre-trained models
