### ISSUE TITLE
crash:  Message from debugger: Terminated due to signal 9

### ISSUE THREAD

**Issue by yunzixun** [william0wang/MagicCamera#2]
take a photo on real device will crash

**Comment by william0wang** [comment]
I test it on iPhoneX and iPad, it is works fine.

Can you provide crash log and describe the problem in detail

**Comment by william0wang** [comment]
> take a photo on real device will crash

I test it on iPhoneX and iPad, it is works fine.

Can you provide crash log and describe the problem in detail
